# Generated by Django 5.2.7 on 2025-10-26 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='images/accounts/', validators=[django.core.validators.FileExtensionValidator(('png', 'jpg', 'jpeg'), 'Не разрешенный формат')]),
        ),
    ]
