# Generated by Django 5.2.7 on 2025-10-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_slug_post_slugs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slugs',
            new_name='slug',
        ),
    ]
