# Generated by Django 5.2.5 on 2025-08-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['create'], name='blog_commen_create_79e65b_idx'),
        ),
    ]
